// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function GetQuote() {
  return window['go']['main']['App']['GetQuote']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LoadCustomSound(arg1) {
  return window['go']['main']['App']['LoadCustomSound'](arg1);
}

export function MoveBy(arg1, arg2) {
  return window['go']['main']['App']['MoveBy'](arg1, arg2);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function OpenSponsor() {
  return window['go']['main']['App']['OpenSponsor']();
}

export function PickCustomSound(arg1) {
  return window['go']['main']['App']['PickCustomSound'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDash(arg1) {
  return window['go']['main']['App']['StartDash'](arg1);
}

export function StopDash() {
  return window['go']['main']['App']['StopDash']();
}
