// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSettings():Promise<void>;

export function GetQuote():Promise<main.Quote>;

export function GetSettings():Promise<main.Settings>;

export function LoadCustomSound(arg1:string):Promise<string>;

export function MoveBy(arg1:number,arg2:number):Promise<void>;

export function OpenSettings():Promise<void>;

export function OpenSponsor():Promise<void>;

export function PickCustomSound(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function StartDash(arg1:number):Promise<void>;

export function StopDash():Promise<void>;
